name: mip_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_database: ^11.3.1
  firebase_storage: ^12.4.1
  permission_handler: ^11.3.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  location: ^5.0.0
  image_picker: ^1.0.7
  get: ^4.6.6
  dropdown_search: ^5.0.0
  material_design_icons_flutter: ^7.0.7296
  google_fonts: 6.1.0
  intl: ^0.18.0
  syncfusion_flutter_pdf: ^23.1.44
  syncfusion_flutter_charts: ^23.1.44
  flutter_vector_icons: ^2.0.0
  side_navigation: ^1.0.4
  mask_text_input_formatter: ^2.9.0
  toggle_switch: ^2.1.0
  image_picker_web: ^2.0.2
  url_launcher: ^6.1.0
  qrcode_reader_web: ^1.1.1
  syncfusion_flutter_barcodes: ^23.1.44
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  map_picker: ^0.0.3
  geocoding: ^3.0.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/
    - assets/map/
    - assets/images/
    - themes/


  
